steps:
# Install dependencies and build
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'bash'
    args: ['-c', 'cd backend/negocio/msa-agent && npm install --quiet && npm run build:function']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'agentHackatonService'
      - '--region=us-central1'
      - '--memory=512MB'
      - '--allow-unauthenticated'
      - '--trigger-http'
      - '--runtime=nodejs20'
      - '--source=./backend/canal/msa-agent/dist'
      - '--set-env-vars=NEAR_ACCOUNT_ID=,NEAR_PRIVATE_KEY=,NEAR_CONTRACT_ID='
      - '--entry-point=authHandler'
options:
  logging: CLOUD_LOGGING_ONLY
serviceAccount: '1094025365695-compute@developer.gserviceaccount.com'
